name: MacOS Release Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_PATH: out
  BUILD_TYPE: release
  BUILD_PLATFORM: macos

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake -S . -B ${{env.BUILD_PATH}} --preset=${{matrix.arch}}-${{env.BUILD_TYPE}}-${{env.BUILD_PLATFORM}}

      - name: Build Project
        run: cat ./${{env.BUILD_PATH}}/resource.c && cmake --build ${{env.BUILD_PATH}} --config ${{env.BUILD_TYPE}} --target wispy

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wipsy-${{env.BUILD_PLATFORM}}-${{matrix.arch}}
          path: ./${{env.BUILD_PATH}}/wispy
